apiVersion: batch/v1
kind: Job
metadata:
  name: sample-clean-job
  namespace: ukjang
  labels:
    cleanup: "true"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: busybox
          image: busybox
          command: ["sh", "-c", "echo cleaning-test && sleep 2"]
